// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: structs.proto

package strutcspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Struct1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field1 int64 `protobuf:"varint,1,opt,name=field1,proto3" json:"field1,omitempty"`
	Field2 bool  `protobuf:"varint,2,opt,name=field2,proto3" json:"field2,omitempty"`
	Field3 bool  `protobuf:"varint,3,opt,name=field3,proto3" json:"field3,omitempty"`
}

func (x *Struct1) Reset() {
	*x = Struct1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_structs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Struct1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Struct1) ProtoMessage() {}

func (x *Struct1) ProtoReflect() protoreflect.Message {
	mi := &file_structs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Struct1.ProtoReflect.Descriptor instead.
func (*Struct1) Descriptor() ([]byte, []int) {
	return file_structs_proto_rawDescGZIP(), []int{0}
}

func (x *Struct1) GetField1() int64 {
	if x != nil {
		return x.Field1
	}
	return 0
}

func (x *Struct1) GetField2() bool {
	if x != nil {
		return x.Field2
	}
	return false
}

func (x *Struct1) GetField3() bool {
	if x != nil {
		return x.Field3
	}
	return false
}

type Struct2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field1 bool  `protobuf:"varint,1,opt,name=field1,proto3" json:"field1,omitempty"`
	Field2 int64 `protobuf:"varint,2,opt,name=field2,proto3" json:"field2,omitempty"`
	Field3 bool  `protobuf:"varint,3,opt,name=field3,proto3" json:"field3,omitempty"`
}

func (x *Struct2) Reset() {
	*x = Struct2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_structs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Struct2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Struct2) ProtoMessage() {}

func (x *Struct2) ProtoReflect() protoreflect.Message {
	mi := &file_structs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Struct2.ProtoReflect.Descriptor instead.
func (*Struct2) Descriptor() ([]byte, []int) {
	return file_structs_proto_rawDescGZIP(), []int{1}
}

func (x *Struct2) GetField1() bool {
	if x != nil {
		return x.Field1
	}
	return false
}

func (x *Struct2) GetField2() int64 {
	if x != nil {
		return x.Field2
	}
	return 0
}

func (x *Struct2) GetField3() bool {
	if x != nil {
		return x.Field3
	}
	return false
}

type Struct3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field1 bool  `protobuf:"varint,1,opt,name=field1,proto3" json:"field1,omitempty"`
	Field2 bool  `protobuf:"varint,2,opt,name=field2,proto3" json:"field2,omitempty"`
	Field3 int64 `protobuf:"varint,3,opt,name=field3,proto3" json:"field3,omitempty"`
}

func (x *Struct3) Reset() {
	*x = Struct3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_structs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Struct3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Struct3) ProtoMessage() {}

func (x *Struct3) ProtoReflect() protoreflect.Message {
	mi := &file_structs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Struct3.ProtoReflect.Descriptor instead.
func (*Struct3) Descriptor() ([]byte, []int) {
	return file_structs_proto_rawDescGZIP(), []int{2}
}

func (x *Struct3) GetField1() bool {
	if x != nil {
		return x.Field1
	}
	return false
}

func (x *Struct3) GetField2() bool {
	if x != nil {
		return x.Field2
	}
	return false
}

func (x *Struct3) GetField3() int64 {
	if x != nil {
		return x.Field3
	}
	return 0
}

var File_structs_proto protoreflect.FileDescriptor

var file_structs_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x51, 0x0a, 0x07, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x33, 0x22, 0x51, 0x0a, 0x07, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x32, 0x12, 0x16, 0x0a,
	0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x12, 0x16, 0x0a,
	0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x33, 0x22, 0x51, 0x0a, 0x07, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x33,
	0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x32,
	0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x33, 0x42, 0x0c, 0x5a, 0x0a, 0x2f, 0x73, 0x74, 0x72,
	0x75, 0x74, 0x63, 0x73, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_structs_proto_rawDescOnce sync.Once
	file_structs_proto_rawDescData = file_structs_proto_rawDesc
)

func file_structs_proto_rawDescGZIP() []byte {
	file_structs_proto_rawDescOnce.Do(func() {
		file_structs_proto_rawDescData = protoimpl.X.CompressGZIP(file_structs_proto_rawDescData)
	})
	return file_structs_proto_rawDescData
}

var file_structs_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_structs_proto_goTypes = []interface{}{
	(*Struct1)(nil), // 0: Struct1
	(*Struct2)(nil), // 1: Struct2
	(*Struct3)(nil), // 2: Struct3
}
var file_structs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_structs_proto_init() }
func file_structs_proto_init() {
	if File_structs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_structs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Struct1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_structs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Struct2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_structs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Struct3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_structs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_structs_proto_goTypes,
		DependencyIndexes: file_structs_proto_depIdxs,
		MessageInfos:      file_structs_proto_msgTypes,
	}.Build()
	File_structs_proto = out.File
	file_structs_proto_rawDesc = nil
	file_structs_proto_goTypes = nil
	file_structs_proto_depIdxs = nil
}
